/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;
import java.applet.AudioClip;

/**
 *
 * @author Eric Ramirez Santis
 */
public class Batalla extends javax.swing.JFrame {

    /**
     * Creates new form Batalla
     */
    public Batalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTablero = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        PanelCasillas = new javax.swing.JPanel();
        NextPlayer3 = new javax.swing.JLabel();
        NextNick3 = new javax.swing.JLabel();
        jProgressBar3 = new javax.swing.JProgressBar();
        NextPlayer2 = new javax.swing.JLabel();
        NextNick2 = new javax.swing.JLabel();
        jProgressBar2 = new javax.swing.JProgressBar();
        NextPlayer1 = new javax.swing.JLabel();
        NextNick1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        PlayingPNG = new javax.swing.JLabel();
        PlayingNick = new javax.swing.JLabel();
        PlayingVida = new javax.swing.JProgressBar();
        PanelAcciones = new javax.swing.JPanel();
        BotonDados = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        JBInvocar = new javax.swing.JButton();
        JBTrampa = new javax.swing.JButton();
        JLdadosN5 = new javax.swing.JLabel();
        JLdadosN4 = new javax.swing.JLabel();
        JLdadosN3 = new javax.swing.JLabel();
        JLdadosN2 = new javax.swing.JLabel();
        JLDados = new javax.swing.JLabel();
        JLDadosN = new javax.swing.JLabel();
        JLAtacar = new javax.swing.JLabel();
        JLAtacarN = new javax.swing.JLabel();
        JLMagia = new javax.swing.JLabel();
        JLMover = new javax.swing.JLabel();
        JLTrampa = new javax.swing.JLabel();
        JLInvocar = new javax.swing.JLabel();
        FondoAcciones = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DDC USACH");
        setPreferredSize(new java.awt.Dimension(723, 703));
        setResizable(false);
        getContentPane().setLayout(null);

        PanelTablero.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(0, 0, 0)));
        PanelTablero.setAutoscrolls(true);
        PanelTablero.setLayout(null);

        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jInternalFrame1.setBorder(null);
        jInternalFrame1.setAutoscrolls(true);
        jInternalFrame1.setPreferredSize(new java.awt.Dimension(1000, 1026));
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);

        PanelCasillas.setOpaque(false);

        javax.swing.GroupLayout PanelCasillasLayout = new javax.swing.GroupLayout(PanelCasillas);
        PanelCasillas.setLayout(PanelCasillasLayout);
        PanelCasillasLayout.setHorizontalGroup(
            PanelCasillasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
        );
        PanelCasillasLayout.setVerticalGroup(
            PanelCasillasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(PanelCasillas);
        PanelCasillas.setBounds(38, 38, 930, 930);

        jScrollPane2.setViewportView(jInternalFrame1);

        PanelTablero.add(jScrollPane2);
        jScrollPane2.setBounds(0, -30, 540, 540);

        getContentPane().add(PanelTablero);
        PanelTablero.setBounds(20, 20, 540, 510);

        NextPlayer3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/PNJ3.png"))); // NOI18N
        NextPlayer3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        NextPlayer3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 3));
        NextPlayer3.setFocusable(false);
        getContentPane().add(NextPlayer3);
        NextPlayer3.setBounds(580, 370, 100, 100);

        NextNick3.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        NextNick3.setForeground(new java.awt.Color(255, 255, 255));
        NextNick3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NextNick3.setText("Tea");
        NextNick3.setFocusable(false);
        getContentPane().add(NextNick3);
        NextNick3.setBounds(580, 350, 100, 20);

        jProgressBar3.setValue(76);
        jProgressBar3.setFocusable(false);
        getContentPane().add(jProgressBar3);
        jProgressBar3.setBounds(580, 470, 100, 14);

        NextPlayer2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/PNJ7.png"))); // NOI18N
        NextPlayer2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        NextPlayer2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));
        NextPlayer2.setFocusable(false);
        getContentPane().add(NextPlayer2);
        NextPlayer2.setBounds(580, 210, 100, 100);

        NextNick2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        NextNick2.setForeground(new java.awt.Color(255, 255, 255));
        NextNick2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NextNick2.setText("Duke");
        NextNick2.setFocusable(false);
        getContentPane().add(NextNick2);
        NextNick2.setBounds(580, 190, 100, 20);

        jProgressBar2.setValue(98);
        jProgressBar2.setFocusable(false);
        getContentPane().add(jProgressBar2);
        jProgressBar2.setBounds(580, 310, 100, 14);

        NextPlayer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 4.png"))); // NOI18N
        NextPlayer1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        NextPlayer1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 3));
        NextPlayer1.setFocusable(false);
        getContentPane().add(NextPlayer1);
        NextPlayer1.setBounds(580, 50, 100, 100);

        NextNick1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        NextNick1.setForeground(new java.awt.Color(255, 255, 255));
        NextNick1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NextNick1.setText("Usuario2");
        NextNick1.setFocusable(false);
        getContentPane().add(NextNick1);
        NextNick1.setBounds(580, 30, 100, 20);

        jProgressBar1.setValue(32);
        jProgressBar1.setFocusable(false);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(580, 150, 100, 14);

        PlayingPNG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 7.png"))); // NOI18N
        PlayingPNG.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PlayingPNG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 3));
        PlayingPNG.setFocusable(false);
        getContentPane().add(PlayingPNG);
        PlayingPNG.setBounds(20, 530, 100, 100);

        PlayingNick.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        PlayingNick.setForeground(new java.awt.Color(255, 255, 255));
        PlayingNick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PlayingNick.setText("Usuario");
        PlayingNick.setFocusable(false);
        getContentPane().add(PlayingNick);
        PlayingNick.setBounds(20, 630, 100, 20);

        PlayingVida.setBackground(new java.awt.Color(255, 0, 0));
        PlayingVida.setForeground(new java.awt.Color(0, 255, 0));
        PlayingVida.setMaximum(400);
        PlayingVida.setValue(345);
        PlayingVida.setBorderPainted(false);
        PlayingVida.setFocusable(false);
        PlayingVida.setString("");
        PlayingVida.setStringPainted(true);
        getContentPane().add(PlayingVida);
        PlayingVida.setBounds(20, 650, 640, 17);

        PanelAcciones.setOpaque(false);
        PanelAcciones.setLayout(null);

        BotonDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ETC/IconDice.png"))); // NOI18N
        BotonDados.setContentAreaFilled(false);
        BotonDados.setFocusable(false);
        BotonDados.setPreferredSize(new java.awt.Dimension(50, 50));
        PanelAcciones.add(BotonDados);
        BotonDados.setBounds(30, 9, 50, 50);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ETC/IconAttack.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusable(false);
        PanelAcciones.add(jButton1);
        jButton1.setBounds(95, 5, 60, 59);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ETC/IconMagic.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusable(false);
        PanelAcciones.add(jButton2);
        jButton2.setBounds(186, 5, 60, 59);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ETC/IconMove.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusable(false);
        PanelAcciones.add(jButton3);
        jButton3.setBounds(274, 5, 60, 59);

        JBInvocar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ETC/IconSummon.png"))); // NOI18N
        JBInvocar.setContentAreaFilled(false);
        JBInvocar.setFocusable(false);
        PanelAcciones.add(JBInvocar);
        JBInvocar.setBounds(352, 5, 70, 59);

        JBTrampa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ETC/IconTrap.png"))); // NOI18N
        JBTrampa.setContentAreaFilled(false);
        JBTrampa.setFocusable(false);
        PanelAcciones.add(JBTrampa);
        JBTrampa.setBounds(450, 5, 60, 59);

        JLdadosN5.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        JLdadosN5.setForeground(new java.awt.Color(255, 255, 255));
        JLdadosN5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLdadosN5.setText("2");
        JLdadosN5.setFocusable(false);
        PanelAcciones.add(JLdadosN5);
        JLdadosN5.setBounds(440, 80, 70, 30);

        JLdadosN4.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        JLdadosN4.setForeground(new java.awt.Color(255, 255, 255));
        JLdadosN4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLdadosN4.setText("0");
        JLdadosN4.setFocusable(false);
        PanelAcciones.add(JLdadosN4);
        JLdadosN4.setBounds(350, 80, 80, 30);

        JLdadosN3.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        JLdadosN3.setForeground(new java.awt.Color(255, 255, 255));
        JLdadosN3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLdadosN3.setText("0");
        JLdadosN3.setFocusable(false);
        PanelAcciones.add(JLdadosN3);
        JLdadosN3.setBounds(270, 80, 60, 30);

        JLdadosN2.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        JLdadosN2.setForeground(new java.awt.Color(255, 255, 255));
        JLdadosN2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLdadosN2.setText("3");
        JLdadosN2.setFocusable(false);
        PanelAcciones.add(JLdadosN2);
        JLdadosN2.setBounds(180, 80, 70, 30);

        JLDados.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        JLDados.setForeground(new java.awt.Color(255, 255, 255));
        JLDados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLDados.setText("Dados");
        JLDados.setFocusable(false);
        PanelAcciones.add(JLDados);
        JLDados.setBounds(10, 60, 83, 30);

        JLDadosN.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        JLDadosN.setForeground(new java.awt.Color(255, 255, 255));
        JLDadosN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLDadosN.setText("4");
        JLDadosN.setFocusable(false);
        PanelAcciones.add(JLDadosN);
        JLDadosN.setBounds(20, 80, 60, 30);

        JLAtacar.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        JLAtacar.setForeground(new java.awt.Color(255, 255, 255));
        JLAtacar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLAtacar.setText("Atacar");
        JLAtacar.setFocusable(false);
        PanelAcciones.add(JLAtacar);
        JLAtacar.setBounds(90, 60, 70, 30);

        JLAtacarN.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        JLAtacarN.setForeground(new java.awt.Color(255, 255, 255));
        JLAtacarN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLAtacarN.setText("1");
        JLAtacarN.setFocusable(false);
        PanelAcciones.add(JLAtacarN);
        JLAtacarN.setBounds(90, 80, 70, 30);

        JLMagia.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        JLMagia.setForeground(new java.awt.Color(255, 255, 255));
        JLMagia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLMagia.setText("Magia");
        JLMagia.setFocusable(false);
        PanelAcciones.add(JLMagia);
        JLMagia.setBounds(180, 60, 70, 30);

        JLMover.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        JLMover.setForeground(new java.awt.Color(255, 255, 255));
        JLMover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLMover.setText("Mover");
        JLMover.setFocusable(false);
        PanelAcciones.add(JLMover);
        JLMover.setBounds(273, 60, 60, 30);

        JLTrampa.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        JLTrampa.setForeground(new java.awt.Color(255, 255, 255));
        JLTrampa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLTrampa.setText("Trampa");
        JLTrampa.setFocusable(false);
        PanelAcciones.add(JLTrampa);
        JLTrampa.setBounds(443, 60, 70, 30);

        JLInvocar.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        JLInvocar.setForeground(new java.awt.Color(255, 255, 255));
        JLInvocar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLInvocar.setText("Invocar");
        JLInvocar.setFocusable(false);
        PanelAcciones.add(JLInvocar);
        JLInvocar.setBounds(353, 60, 70, 30);

        FondoAcciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/BGBlack.png"))); // NOI18N
        FondoAcciones.setFocusable(false);
        PanelAcciones.add(FondoAcciones);
        FondoAcciones.setBounds(0, 0, 550, 120);

        getContentPane().add(PanelAcciones);
        PanelAcciones.setBounds(120, 530, 550, 120);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/Fondo.png"))); // NOI18N
        Fondo.setFocusable(false);
        getContentPane().add(Fondo);
        Fondo.setBounds(0, 0, 700, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonDados;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel FondoAcciones;
    private javax.swing.JButton JBInvocar;
    private javax.swing.JButton JBTrampa;
    private javax.swing.JLabel JLAtacar;
    private javax.swing.JLabel JLAtacarN;
    private javax.swing.JLabel JLDados;
    private javax.swing.JLabel JLDadosN;
    private javax.swing.JLabel JLInvocar;
    private javax.swing.JLabel JLMagia;
    private javax.swing.JLabel JLMover;
    private javax.swing.JLabel JLTrampa;
    private javax.swing.JLabel JLdadosN2;
    private javax.swing.JLabel JLdadosN3;
    private javax.swing.JLabel JLdadosN4;
    private javax.swing.JLabel JLdadosN5;
    private javax.swing.JLabel NextNick1;
    private javax.swing.JLabel NextNick2;
    private javax.swing.JLabel NextNick3;
    private javax.swing.JLabel NextPlayer1;
    private javax.swing.JLabel NextPlayer2;
    private javax.swing.JLabel NextPlayer3;
    private javax.swing.JPanel PanelAcciones;
    private javax.swing.JPanel PanelCasillas;
    private javax.swing.JPanel PanelTablero;
    private javax.swing.JLabel PlayingNick;
    private javax.swing.JLabel PlayingPNG;
    private javax.swing.JProgressBar PlayingVida;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
