/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;
import java.applet.AudioClip;
import java.awt.Dimension;

/**
 *
 * @author Eric Ramirez Santis
 */
public class Batalla extends javax.swing.JFrame {

    /**
     * Creates new form Batalla
     */
    public Batalla() {
        initComponents();
        this.setMinimumSize(new Dimension(723,703));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTablero = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        X1Y1 = new javax.swing.JLabel();
        X1Y2 = new javax.swing.JLabel();
        X1Y3 = new javax.swing.JLabel();
        X1Y4 = new javax.swing.JLabel();
        X1Y5 = new javax.swing.JLabel();
        X1Y6 = new javax.swing.JLabel();
        X1Y7 = new javax.swing.JLabel();
        X1Y8 = new javax.swing.JLabel();
        X1Y9 = new javax.swing.JLabel();
        X1Y10 = new javax.swing.JLabel();
        X1Y11 = new javax.swing.JLabel();
        X1Y12 = new javax.swing.JLabel();
        X1Y13 = new javax.swing.JLabel();
        X1Y14 = new javax.swing.JLabel();
        X1Y15 = new javax.swing.JLabel();
        X2Y1 = new javax.swing.JLabel();
        X2Y2 = new javax.swing.JLabel();
        X2Y3 = new javax.swing.JLabel();
        X2Y4 = new javax.swing.JLabel();
        X2Y5 = new javax.swing.JLabel();
        X2Y6 = new javax.swing.JLabel();
        X2Y7 = new javax.swing.JLabel();
        X2Y8 = new javax.swing.JLabel();
        X2Y9 = new javax.swing.JLabel();
        X2Y10 = new javax.swing.JLabel();
        X2Y11 = new javax.swing.JLabel();
        X2Y12 = new javax.swing.JLabel();
        X2Y13 = new javax.swing.JLabel();
        X2Y14 = new javax.swing.JLabel();
        X2Y15 = new javax.swing.JLabel();
        X3Y1 = new javax.swing.JLabel();
        X3Y2 = new javax.swing.JLabel();
        X3Y3 = new javax.swing.JLabel();
        X3Y4 = new javax.swing.JLabel();
        X3Y5 = new javax.swing.JLabel();
        X3Y6 = new javax.swing.JLabel();
        X3Y7 = new javax.swing.JLabel();
        X3Y8 = new javax.swing.JLabel();
        X3Y9 = new javax.swing.JLabel();
        X3Y10 = new javax.swing.JLabel();
        X3Y11 = new javax.swing.JLabel();
        X3Y12 = new javax.swing.JLabel();
        X3Y13 = new javax.swing.JLabel();
        X3Y14 = new javax.swing.JLabel();
        X3Y15 = new javax.swing.JLabel();
        X4Y1 = new javax.swing.JLabel();
        X4Y2 = new javax.swing.JLabel();
        X4Y3 = new javax.swing.JLabel();
        X4Y4 = new javax.swing.JLabel();
        X4Y5 = new javax.swing.JLabel();
        X4Y6 = new javax.swing.JLabel();
        X4Y7 = new javax.swing.JLabel();
        X4Y8 = new javax.swing.JLabel();
        X4Y9 = new javax.swing.JLabel();
        X4Y10 = new javax.swing.JLabel();
        X4Y11 = new javax.swing.JLabel();
        X4Y12 = new javax.swing.JLabel();
        X4Y13 = new javax.swing.JLabel();
        X4Y14 = new javax.swing.JLabel();
        X4Y15 = new javax.swing.JLabel();
        X5Y1 = new javax.swing.JLabel();
        X5Y2 = new javax.swing.JLabel();
        X5Y3 = new javax.swing.JLabel();
        X5Y4 = new javax.swing.JLabel();
        X5Y5 = new javax.swing.JLabel();
        X5Y6 = new javax.swing.JLabel();
        X5Y7 = new javax.swing.JLabel();
        X5Y8 = new javax.swing.JLabel();
        X5Y9 = new javax.swing.JLabel();
        X5Y10 = new javax.swing.JLabel();
        X5Y11 = new javax.swing.JLabel();
        X5Y12 = new javax.swing.JLabel();
        X5Y13 = new javax.swing.JLabel();
        X5Y14 = new javax.swing.JLabel();
        X5Y15 = new javax.swing.JLabel();
        X6Y1 = new javax.swing.JLabel();
        X6Y2 = new javax.swing.JLabel();
        X6Y3 = new javax.swing.JLabel();
        X6Y4 = new javax.swing.JLabel();
        X6Y5 = new javax.swing.JLabel();
        X6Y6 = new javax.swing.JLabel();
        X6Y7 = new javax.swing.JLabel();
        X6Y8 = new javax.swing.JLabel();
        X6Y9 = new javax.swing.JLabel();
        X6Y10 = new javax.swing.JLabel();
        X6Y11 = new javax.swing.JLabel();
        X6Y12 = new javax.swing.JLabel();
        X6Y13 = new javax.swing.JLabel();
        X6Y14 = new javax.swing.JLabel();
        X6Y15 = new javax.swing.JLabel();
        X7Y1 = new javax.swing.JLabel();
        X7Y2 = new javax.swing.JLabel();
        X7Y3 = new javax.swing.JLabel();
        X7Y4 = new javax.swing.JLabel();
        X7Y5 = new javax.swing.JLabel();
        X7Y6 = new javax.swing.JLabel();
        X7Y7 = new javax.swing.JLabel();
        X7Y8 = new javax.swing.JLabel();
        X7Y9 = new javax.swing.JLabel();
        X7Y10 = new javax.swing.JLabel();
        X7Y11 = new javax.swing.JLabel();
        X7Y12 = new javax.swing.JLabel();
        X7Y13 = new javax.swing.JLabel();
        X7Y14 = new javax.swing.JLabel();
        X7Y15 = new javax.swing.JLabel();
        X8Y1 = new javax.swing.JLabel();
        X8Y2 = new javax.swing.JLabel();
        X8Y3 = new javax.swing.JLabel();
        X8Y4 = new javax.swing.JLabel();
        X8Y5 = new javax.swing.JLabel();
        X8Y6 = new javax.swing.JLabel();
        X8Y7 = new javax.swing.JLabel();
        X8Y8 = new javax.swing.JLabel();
        X8Y9 = new javax.swing.JLabel();
        X8Y10 = new javax.swing.JLabel();
        X8Y11 = new javax.swing.JLabel();
        X8Y12 = new javax.swing.JLabel();
        X8Y13 = new javax.swing.JLabel();
        X8Y14 = new javax.swing.JLabel();
        X8Y15 = new javax.swing.JLabel();
        X9Y1 = new javax.swing.JLabel();
        X9Y2 = new javax.swing.JLabel();
        X9Y3 = new javax.swing.JLabel();
        X9Y4 = new javax.swing.JLabel();
        X9Y5 = new javax.swing.JLabel();
        X9Y6 = new javax.swing.JLabel();
        X9Y7 = new javax.swing.JLabel();
        X9Y8 = new javax.swing.JLabel();
        X9Y9 = new javax.swing.JLabel();
        X9Y10 = new javax.swing.JLabel();
        X9Y11 = new javax.swing.JLabel();
        X9Y12 = new javax.swing.JLabel();
        X9Y13 = new javax.swing.JLabel();
        X9Y14 = new javax.swing.JLabel();
        X9Y15 = new javax.swing.JLabel();
        X10Y1 = new javax.swing.JLabel();
        X10Y2 = new javax.swing.JLabel();
        X10Y3 = new javax.swing.JLabel();
        X10Y4 = new javax.swing.JLabel();
        X10Y5 = new javax.swing.JLabel();
        X10Y6 = new javax.swing.JLabel();
        X10Y7 = new javax.swing.JLabel();
        X10Y8 = new javax.swing.JLabel();
        X10Y9 = new javax.swing.JLabel();
        X10Y10 = new javax.swing.JLabel();
        X10Y11 = new javax.swing.JLabel();
        X10Y12 = new javax.swing.JLabel();
        X10Y13 = new javax.swing.JLabel();
        X10Y14 = new javax.swing.JLabel();
        X10Y15 = new javax.swing.JLabel();
        X11Y1 = new javax.swing.JLabel();
        X11Y2 = new javax.swing.JLabel();
        X11Y3 = new javax.swing.JLabel();
        X11Y4 = new javax.swing.JLabel();
        X11Y5 = new javax.swing.JLabel();
        X11Y6 = new javax.swing.JLabel();
        X11Y7 = new javax.swing.JLabel();
        X11Y8 = new javax.swing.JLabel();
        X11Y9 = new javax.swing.JLabel();
        X11Y10 = new javax.swing.JLabel();
        X11Y11 = new javax.swing.JLabel();
        X11Y12 = new javax.swing.JLabel();
        X11Y13 = new javax.swing.JLabel();
        X11Y14 = new javax.swing.JLabel();
        X11Y15 = new javax.swing.JLabel();
        X12Y1 = new javax.swing.JLabel();
        X12Y2 = new javax.swing.JLabel();
        X12Y3 = new javax.swing.JLabel();
        X12Y4 = new javax.swing.JLabel();
        X12Y5 = new javax.swing.JLabel();
        X12Y6 = new javax.swing.JLabel();
        X12Y7 = new javax.swing.JLabel();
        X12Y8 = new javax.swing.JLabel();
        X12Y9 = new javax.swing.JLabel();
        X12Y10 = new javax.swing.JLabel();
        X12Y11 = new javax.swing.JLabel();
        X12Y12 = new javax.swing.JLabel();
        X12Y13 = new javax.swing.JLabel();
        X12Y14 = new javax.swing.JLabel();
        X12Y15 = new javax.swing.JLabel();
        X13Y1 = new javax.swing.JLabel();
        X13Y2 = new javax.swing.JLabel();
        X13Y3 = new javax.swing.JLabel();
        X13Y4 = new javax.swing.JLabel();
        X13Y5 = new javax.swing.JLabel();
        X13Y6 = new javax.swing.JLabel();
        X13Y7 = new javax.swing.JLabel();
        X13Y8 = new javax.swing.JLabel();
        X13Y9 = new javax.swing.JLabel();
        X13Y10 = new javax.swing.JLabel();
        X13Y11 = new javax.swing.JLabel();
        X13Y12 = new javax.swing.JLabel();
        X13Y13 = new javax.swing.JLabel();
        X13Y14 = new javax.swing.JLabel();
        X13Y15 = new javax.swing.JLabel();
        X14Y1 = new javax.swing.JLabel();
        X14Y2 = new javax.swing.JLabel();
        X14Y3 = new javax.swing.JLabel();
        X14Y4 = new javax.swing.JLabel();
        X14Y5 = new javax.swing.JLabel();
        X14Y6 = new javax.swing.JLabel();
        X14Y7 = new javax.swing.JLabel();
        X14Y8 = new javax.swing.JLabel();
        X14Y9 = new javax.swing.JLabel();
        X14Y10 = new javax.swing.JLabel();
        X14Y11 = new javax.swing.JLabel();
        X14Y12 = new javax.swing.JLabel();
        X14Y13 = new javax.swing.JLabel();
        X14Y14 = new javax.swing.JLabel();
        X14Y15 = new javax.swing.JLabel();
        X15Y1 = new javax.swing.JLabel();
        X15Y2 = new javax.swing.JLabel();
        X15Y3 = new javax.swing.JLabel();
        X15Y4 = new javax.swing.JLabel();
        X15Y5 = new javax.swing.JLabel();
        X15Y6 = new javax.swing.JLabel();
        X15Y7 = new javax.swing.JLabel();
        X15Y8 = new javax.swing.JLabel();
        X15Y9 = new javax.swing.JLabel();
        X15Y10 = new javax.swing.JLabel();
        X15Y11 = new javax.swing.JLabel();
        X15Y12 = new javax.swing.JLabel();
        X15Y13 = new javax.swing.JLabel();
        X15Y14 = new javax.swing.JLabel();
        X15Y15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NextPlayer3 = new javax.swing.JLabel();
        NextNick3 = new javax.swing.JLabel();
        jProgressBar3 = new javax.swing.JProgressBar();
        NextPlayer2 = new javax.swing.JLabel();
        NextNick2 = new javax.swing.JLabel();
        jProgressBar2 = new javax.swing.JProgressBar();
        NextPlayer1 = new javax.swing.JLabel();
        NextNick1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        PlayingPNG = new javax.swing.JLabel();
        PlayingNick = new javax.swing.JLabel();
        PlayingVida = new javax.swing.JProgressBar();
        PanelAcciones = new javax.swing.JPanel();
        BotonDados = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        JBInvocar = new javax.swing.JButton();
        JBTrampa = new javax.swing.JButton();
        JLdadosN5 = new javax.swing.JLabel();
        JLdadosN4 = new javax.swing.JLabel();
        JLdadosN3 = new javax.swing.JLabel();
        JLdadosN2 = new javax.swing.JLabel();
        JLDados = new javax.swing.JLabel();
        JLDadosN = new javax.swing.JLabel();
        JLAtacar = new javax.swing.JLabel();
        JLAtacarN = new javax.swing.JLabel();
        JLMagia = new javax.swing.JLabel();
        JLMover = new javax.swing.JLabel();
        JLTrampa = new javax.swing.JLabel();
        JLInvocar = new javax.swing.JLabel();
        FondoAcciones = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DDC USACH");
        setMinimumSize(new java.awt.Dimension(723, 703));
        setResizable(false);
        getContentPane().setLayout(null);

        PanelTablero.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(0, 0, 0)));
        PanelTablero.setAutoscrolls(true);
        PanelTablero.setLayout(null);

        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jInternalFrame1.setBorder(null);
        jInternalFrame1.setAutoscrolls(true);
        jInternalFrame1.setPreferredSize(new java.awt.Dimension(1000, 1026));
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        X1Y1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        X1Y1.setToolTipText("1,1");
        jPanel2.add(X1Y1);
        X1Y1.setBounds(0, 0, 60, 60);

        X1Y2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X1Y2);
        X1Y2.setBounds(0, 62, 60, 60);

        X1Y3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X1Y3);
        X1Y3.setBounds(0, 124, 60, 60);

        X1Y4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X1Y4);
        X1Y4.setBounds(0, 186, 60, 60);

        X1Y5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X1Y5);
        X1Y5.setBounds(0, 248, 60, 60);

        X1Y6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X1Y6);
        X1Y6.setBounds(0, 310, 60, 60);

        X1Y7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X1Y7);
        X1Y7.setBounds(0, 372, 60, 60);

        X1Y8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X1Y8);
        X1Y8.setBounds(0, 434, 60, 60);

        X1Y9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X1Y9);
        X1Y9.setBounds(0, 497, 60, 60);

        X1Y10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X1Y10);
        X1Y10.setBounds(0, 558, 60, 60);

        X1Y11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X1Y11);
        X1Y11.setBounds(0, 620, 60, 60);

        X1Y12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X1Y12);
        X1Y12.setBounds(0, 682, 60, 60);

        X1Y13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X1Y13);
        X1Y13.setBounds(0, 744, 60, 60);

        X1Y14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X1Y14);
        X1Y14.setBounds(0, 807, 60, 60);

        X1Y15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X1Y15);
        X1Y15.setBounds(0, 869, 60, 60);

        X2Y1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        X2Y1.setToolTipText("2,1");
        jPanel2.add(X2Y1);
        X2Y1.setBounds(62, 0, 60, 60);

        X2Y2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X2Y2);
        X2Y2.setBounds(62, 62, 60, 60);

        X2Y3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X2Y3);
        X2Y3.setBounds(62, 124, 60, 60);

        X2Y4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X2Y4);
        X2Y4.setBounds(62, 186, 60, 60);

        X2Y5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X2Y5);
        X2Y5.setBounds(62, 248, 60, 60);

        X2Y6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X2Y6);
        X2Y6.setBounds(62, 310, 60, 60);

        X2Y7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X2Y7);
        X2Y7.setBounds(62, 372, 60, 60);

        X2Y8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X2Y8);
        X2Y8.setBounds(62, 434, 60, 60);

        X2Y9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X2Y9);
        X2Y9.setBounds(62, 497, 60, 60);

        X2Y10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X2Y10);
        X2Y10.setBounds(62, 558, 60, 60);

        X2Y11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X2Y11);
        X2Y11.setBounds(62, 620, 60, 60);

        X2Y12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X2Y12);
        X2Y12.setBounds(62, 682, 60, 60);

        X2Y13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X2Y13);
        X2Y13.setBounds(62, 744, 60, 60);

        X2Y14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X2Y14);
        X2Y14.setBounds(62, 807, 60, 60);

        X2Y15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X2Y15);
        X2Y15.setBounds(62, 869, 60, 60);

        X3Y1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        X3Y1.setToolTipText("3,1");
        jPanel2.add(X3Y1);
        X3Y1.setBounds(124, 0, 60, 60);

        X3Y2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X3Y2);
        X3Y2.setBounds(124, 62, 60, 60);

        X3Y3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X3Y3);
        X3Y3.setBounds(124, 124, 60, 60);

        X3Y4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X3Y4);
        X3Y4.setBounds(124, 186, 60, 60);

        X3Y5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X3Y5);
        X3Y5.setBounds(124, 248, 60, 60);

        X3Y6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X3Y6);
        X3Y6.setBounds(124, 310, 60, 60);

        X3Y7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X3Y7);
        X3Y7.setBounds(124, 372, 60, 60);

        X3Y8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X3Y8);
        X3Y8.setBounds(124, 434, 60, 60);

        X3Y9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X3Y9);
        X3Y9.setBounds(124, 497, 60, 60);

        X3Y10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X3Y10);
        X3Y10.setBounds(124, 558, 60, 60);

        X3Y11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X3Y11);
        X3Y11.setBounds(124, 620, 60, 60);

        X3Y12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X3Y12);
        X3Y12.setBounds(124, 682, 60, 60);

        X3Y13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X3Y13);
        X3Y13.setBounds(124, 744, 60, 60);

        X3Y14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X3Y14);
        X3Y14.setBounds(124, 807, 60, 60);

        X3Y15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X3Y15);
        X3Y15.setBounds(124, 869, 60, 60);

        X4Y1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        X4Y1.setToolTipText("4,1");
        jPanel2.add(X4Y1);
        X4Y1.setBounds(186, 0, 60, 60);

        X4Y2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X4Y2);
        X4Y2.setBounds(186, 62, 60, 60);

        X4Y3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X4Y3);
        X4Y3.setBounds(186, 124, 60, 60);

        X4Y4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X4Y4);
        X4Y4.setBounds(186, 186, 60, 60);

        X4Y5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X4Y5);
        X4Y5.setBounds(186, 248, 60, 60);

        X4Y6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X4Y6);
        X4Y6.setBounds(186, 310, 60, 60);

        X4Y7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X4Y7);
        X4Y7.setBounds(186, 372, 60, 60);

        X4Y8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X4Y8);
        X4Y8.setBounds(186, 434, 60, 60);

        X4Y9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X4Y9);
        X4Y9.setBounds(186, 497, 60, 60);

        X4Y10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TVerde.png"))); // NOI18N
        jPanel2.add(X4Y10);
        X4Y10.setBounds(186, 558, 60, 60);

        X4Y11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TVerde.png"))); // NOI18N
        jPanel2.add(X4Y11);
        X4Y11.setBounds(186, 620, 60, 60);

        X4Y12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X4Y12);
        X4Y12.setBounds(186, 682, 60, 60);

        X4Y13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X4Y13);
        X4Y13.setBounds(186, 744, 60, 60);

        X4Y14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X4Y14);
        X4Y14.setBounds(186, 807, 60, 60);

        X4Y15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X4Y15);
        X4Y15.setBounds(186, 869, 60, 60);

        X5Y1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        X5Y1.setToolTipText("5,1");
        jPanel2.add(X5Y1);
        X5Y1.setBounds(248, 0, 60, 60);

        X5Y2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X5Y2);
        X5Y2.setBounds(248, 62, 60, 60);

        X5Y3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X5Y3);
        X5Y3.setBounds(248, 124, 60, 60);

        X5Y4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X5Y4);
        X5Y4.setBounds(248, 186, 60, 60);

        X5Y5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X5Y5);
        X5Y5.setBounds(248, 248, 60, 60);

        X5Y6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X5Y6);
        X5Y6.setBounds(248, 310, 60, 60);

        X5Y7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X5Y7);
        X5Y7.setBounds(248, 372, 60, 60);

        X5Y8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X5Y8);
        X5Y8.setBounds(248, 434, 60, 60);

        X5Y9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X5Y9);
        X5Y9.setBounds(248, 497, 60, 60);

        X5Y10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X5Y10);
        X5Y10.setBounds(248, 558, 60, 60);

        X5Y11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TVerde.png"))); // NOI18N
        jPanel2.add(X5Y11);
        X5Y11.setBounds(248, 620, 60, 60);

        X5Y12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X5Y12);
        X5Y12.setBounds(248, 682, 60, 60);

        X5Y13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X5Y13);
        X5Y13.setBounds(248, 744, 60, 60);

        X5Y14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X5Y14);
        X5Y14.setBounds(248, 807, 60, 60);

        X5Y15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X5Y15);
        X5Y15.setBounds(248, 869, 60, 60);

        X6Y1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        X6Y1.setToolTipText("6,1");
        jPanel2.add(X6Y1);
        X6Y1.setBounds(310, 0, 60, 60);

        X6Y2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X6Y2);
        X6Y2.setBounds(310, 62, 60, 60);

        X6Y3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X6Y3);
        X6Y3.setBounds(310, 124, 60, 60);

        X6Y4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X6Y4);
        X6Y4.setBounds(310, 186, 60, 60);

        X6Y5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X6Y5);
        X6Y5.setBounds(310, 248, 60, 60);

        X6Y6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X6Y6);
        X6Y6.setBounds(310, 310, 60, 60);

        X6Y7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X6Y7);
        X6Y7.setBounds(310, 372, 60, 60);

        X6Y8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X6Y8);
        X6Y8.setBounds(310, 434, 60, 60);

        X6Y9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X6Y9);
        X6Y9.setBounds(310, 497, 60, 60);

        X6Y10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X6Y10);
        X6Y10.setBounds(310, 558, 60, 60);

        X6Y11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TVerde.png"))); // NOI18N
        jPanel2.add(X6Y11);
        X6Y11.setBounds(310, 620, 60, 60);

        X6Y12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X6Y12);
        X6Y12.setBounds(310, 682, 60, 60);

        X6Y13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X6Y13);
        X6Y13.setBounds(310, 744, 60, 60);

        X6Y14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X6Y14);
        X6Y14.setBounds(310, 807, 60, 60);

        X6Y15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X6Y15);
        X6Y15.setBounds(310, 869, 60, 60);

        X7Y1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        X7Y1.setToolTipText("7,1");
        jPanel2.add(X7Y1);
        X7Y1.setBounds(373, 0, 60, 60);

        X7Y2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X7Y2);
        X7Y2.setBounds(373, 62, 60, 60);

        X7Y3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X7Y3);
        X7Y3.setBounds(373, 124, 60, 60);

        X7Y4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X7Y4);
        X7Y4.setBounds(373, 186, 60, 60);

        X7Y5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X7Y5);
        X7Y5.setBounds(373, 248, 60, 60);

        X7Y6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X7Y6);
        X7Y6.setBounds(373, 310, 60, 60);
        jPanel2.add(X7Y7);
        X7Y7.setBounds(373, 372, 0, 0);
        jPanel2.add(X7Y8);
        X7Y8.setBounds(373, 434, 0, 0);

        X7Y9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X7Y9);
        X7Y9.setBounds(373, 497, 60, 60);

        X7Y10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X7Y10);
        X7Y10.setBounds(373, 558, 60, 60);

        X7Y11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TVerde.png"))); // NOI18N
        jPanel2.add(X7Y11);
        X7Y11.setBounds(373, 620, 60, 60);

        X7Y12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TVerde.png"))); // NOI18N
        jPanel2.add(X7Y12);
        X7Y12.setBounds(373, 682, 60, 60);

        X7Y13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TAzul.png"))); // NOI18N
        jPanel2.add(X7Y13);
        X7Y13.setBounds(373, 744, 60, 60);

        X7Y14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X7Y14);
        X7Y14.setBounds(373, 807, 60, 60);

        X7Y15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X7Y15);
        X7Y15.setBounds(373, 869, 60, 60);

        X8Y1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        X8Y1.setToolTipText("8,1");
        jPanel2.add(X8Y1);
        X8Y1.setBounds(434, 0, 60, 60);

        X8Y2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X8Y2);
        X8Y2.setBounds(434, 62, 60, 60);

        X8Y3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X8Y3);
        X8Y3.setBounds(434, 124, 60, 60);

        X8Y4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X8Y4);
        X8Y4.setBounds(434, 186, 60, 60);

        X8Y5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X8Y5);
        X8Y5.setBounds(434, 248, 60, 60);

        X8Y6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X8Y6);
        X8Y6.setBounds(434, 310, 60, 60);

        X8Y7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X8Y7);
        X8Y7.setBounds(434, 372, 60, 60);

        X8Y8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TRojo.png"))); // NOI18N
        jPanel2.add(X8Y8);
        X8Y8.setBounds(434, 434, 60, 60);

        X8Y9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TRojo.png"))); // NOI18N
        jPanel2.add(X8Y9);
        X8Y9.setBounds(434, 497, 60, 60);

        X8Y10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X8Y10);
        X8Y10.setBounds(434, 558, 60, 60);

        X8Y11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X8Y11);
        X8Y11.setBounds(434, 620, 60, 60);

        X8Y12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TAzul.png"))); // NOI18N
        jPanel2.add(X8Y12);
        X8Y12.setBounds(434, 682, 60, 60);

        X8Y13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TAzul.png"))); // NOI18N
        jPanel2.add(X8Y13);
        X8Y13.setBounds(434, 744, 60, 60);

        X8Y14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TAzul.png"))); // NOI18N
        jPanel2.add(X8Y14);
        X8Y14.setBounds(434, 807, 60, 60);

        X8Y15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TAzul.png"))); // NOI18N
        jPanel2.add(X8Y15);
        X8Y15.setBounds(434, 869, 60, 60);

        X9Y1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        X9Y1.setToolTipText("9,1");
        jPanel2.add(X9Y1);
        X9Y1.setBounds(496, 0, 60, 60);

        X9Y2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X9Y2);
        X9Y2.setBounds(496, 62, 60, 60);

        X9Y3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X9Y3);
        X9Y3.setBounds(496, 124, 60, 60);

        X9Y4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X9Y4);
        X9Y4.setBounds(496, 186, 60, 60);

        X9Y5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X9Y5);
        X9Y5.setBounds(496, 248, 60, 60);

        X9Y6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X9Y6);
        X9Y6.setBounds(496, 310, 60, 60);

        X9Y7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X9Y7);
        X9Y7.setBounds(496, 372, 60, 60);

        X9Y8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X9Y8);
        X9Y8.setBounds(496, 434, 60, 60);

        X9Y9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TRojo.png"))); // NOI18N
        jPanel2.add(X9Y9);
        X9Y9.setBounds(496, 497, 60, 60);

        X9Y10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TRojo.png"))); // NOI18N
        jPanel2.add(X9Y10);
        X9Y10.setBounds(496, 558, 60, 60);

        X9Y11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TAmarillo.png"))); // NOI18N
        jPanel2.add(X9Y11);
        X9Y11.setBounds(496, 620, 60, 60);

        X9Y12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TAmarillo.png"))); // NOI18N
        jPanel2.add(X9Y12);
        X9Y12.setBounds(496, 682, 60, 60);

        X9Y13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TAzul.png"))); // NOI18N
        jPanel2.add(X9Y13);
        X9Y13.setBounds(496, 744, 60, 60);

        X9Y14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X9Y14);
        X9Y14.setBounds(496, 807, 60, 60);

        X9Y15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X9Y15);
        X9Y15.setBounds(496, 869, 60, 60);

        X10Y1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        X10Y1.setToolTipText("10,1");
        jPanel2.add(X10Y1);
        X10Y1.setBounds(558, 0, 60, 60);

        X10Y2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X10Y2);
        X10Y2.setBounds(558, 62, 60, 60);

        X10Y3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X10Y3);
        X10Y3.setBounds(558, 124, 60, 60);

        X10Y4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X10Y4);
        X10Y4.setBounds(558, 186, 60, 60);

        X10Y5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X10Y5);
        X10Y5.setBounds(558, 248, 60, 60);

        X10Y6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X10Y6);
        X10Y6.setBounds(558, 310, 60, 60);

        X10Y7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X10Y7);
        X10Y7.setBounds(558, 372, 60, 60);

        X10Y8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X10Y8);
        X10Y8.setBounds(558, 434, 60, 60);

        X10Y9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X10Y9);
        X10Y9.setBounds(558, 497, 60, 60);

        X10Y10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X10Y10);
        X10Y10.setBounds(558, 558, 60, 60);

        X10Y11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X10Y11);
        X10Y11.setBounds(558, 620, 60, 60);

        X10Y12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TAmarillo.png"))); // NOI18N
        jPanel2.add(X10Y12);
        X10Y12.setBounds(558, 682, 60, 60);

        X10Y13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TAmarillo.png"))); // NOI18N
        jPanel2.add(X10Y13);
        X10Y13.setBounds(558, 744, 60, 60);

        X10Y14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TAmarillo.png"))); // NOI18N
        jPanel2.add(X10Y14);
        X10Y14.setBounds(558, 807, 60, 60);

        X10Y15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X10Y15);
        X10Y15.setBounds(558, 869, 60, 60);

        X11Y1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        X11Y1.setToolTipText("11,1");
        jPanel2.add(X11Y1);
        X11Y1.setBounds(621, 0, 60, 60);

        X11Y2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X11Y2);
        X11Y2.setBounds(621, 62, 60, 60);

        X11Y3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X11Y3);
        X11Y3.setBounds(621, 124, 60, 60);

        X11Y4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X11Y4);
        X11Y4.setBounds(621, 186, 60, 60);

        X11Y5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X11Y5);
        X11Y5.setBounds(621, 248, 60, 60);

        X11Y6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X11Y6);
        X11Y6.setBounds(621, 310, 60, 60);

        X11Y7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X11Y7);
        X11Y7.setBounds(621, 372, 60, 60);

        X11Y8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X11Y8);
        X11Y8.setBounds(621, 434, 60, 60);

        X11Y9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X11Y9);
        X11Y9.setBounds(621, 497, 60, 60);

        X11Y10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X11Y10);
        X11Y10.setBounds(621, 558, 60, 60);

        X11Y11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X11Y11);
        X11Y11.setBounds(621, 620, 60, 60);

        X11Y12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X11Y12);
        X11Y12.setBounds(621, 682, 60, 60);

        X11Y13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TAmarillo.png"))); // NOI18N
        jPanel2.add(X11Y13);
        X11Y13.setBounds(621, 744, 60, 60);

        X11Y14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X11Y14);
        X11Y14.setBounds(621, 807, 60, 60);

        X11Y15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X11Y15);
        X11Y15.setBounds(621, 869, 60, 60);

        X12Y1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        X12Y1.setToolTipText("12,1");
        jPanel2.add(X12Y1);
        X12Y1.setBounds(683, 0, 60, 60);

        X12Y2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X12Y2);
        X12Y2.setBounds(683, 62, 60, 60);

        X12Y3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X12Y3);
        X12Y3.setBounds(683, 124, 60, 60);

        X12Y4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X12Y4);
        X12Y4.setBounds(683, 186, 60, 60);

        X12Y5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X12Y5);
        X12Y5.setBounds(683, 248, 60, 60);

        X12Y6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X12Y6);
        X12Y6.setBounds(683, 310, 60, 60);

        X12Y7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X12Y7);
        X12Y7.setBounds(683, 372, 60, 60);

        X12Y8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X12Y8);
        X12Y8.setBounds(683, 434, 60, 60);

        X12Y9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X12Y9);
        X12Y9.setBounds(683, 497, 60, 60);

        X12Y10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X12Y10);
        X12Y10.setBounds(683, 558, 60, 60);

        X12Y11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X12Y11);
        X12Y11.setBounds(683, 620, 60, 60);

        X12Y12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TAmarillo.png"))); // NOI18N
        jPanel2.add(X12Y12);
        X12Y12.setBounds(683, 682, 60, 60);

        X12Y13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TAmarillo.png"))); // NOI18N
        jPanel2.add(X12Y13);
        X12Y13.setBounds(683, 744, 60, 60);

        X12Y14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TAmarillo.png"))); // NOI18N
        jPanel2.add(X12Y14);
        X12Y14.setBounds(683, 807, 60, 60);

        X12Y15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X12Y15);
        X12Y15.setBounds(683, 869, 60, 60);

        X13Y1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        X13Y1.setToolTipText("13,1");
        jPanel2.add(X13Y1);
        X13Y1.setBounds(745, 0, 60, 60);

        X13Y2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X13Y2);
        X13Y2.setBounds(745, 62, 60, 60);

        X13Y3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X13Y3);
        X13Y3.setBounds(745, 124, 60, 60);

        X13Y4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X13Y4);
        X13Y4.setBounds(745, 186, 60, 60);

        X13Y5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X13Y5);
        X13Y5.setBounds(745, 248, 60, 60);

        X13Y6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X13Y6);
        X13Y6.setBounds(745, 310, 60, 60);

        X13Y7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X13Y7);
        X13Y7.setBounds(745, 372, 60, 60);

        X13Y8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X13Y8);
        X13Y8.setBounds(745, 434, 60, 60);

        X13Y9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X13Y9);
        X13Y9.setBounds(745, 497, 60, 60);

        X13Y10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X13Y10);
        X13Y10.setBounds(745, 558, 60, 60);

        X13Y11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X13Y11);
        X13Y11.setBounds(745, 620, 60, 60);

        X13Y12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X13Y12);
        X13Y12.setBounds(745, 682, 60, 60);

        X13Y13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TAmarillo.png"))); // NOI18N
        jPanel2.add(X13Y13);
        X13Y13.setBounds(745, 744, 60, 60);

        X13Y14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X13Y14);
        X13Y14.setBounds(745, 807, 60, 60);

        X13Y15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X13Y15);
        X13Y15.setBounds(745, 869, 60, 60);

        X14Y1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        X14Y1.setToolTipText("14,1");
        jPanel2.add(X14Y1);
        X14Y1.setBounds(807, 0, 60, 60);

        X14Y2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X14Y2);
        X14Y2.setBounds(807, 62, 60, 60);

        X14Y3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X14Y3);
        X14Y3.setBounds(807, 124, 60, 60);

        X14Y4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X14Y4);
        X14Y4.setBounds(807, 186, 60, 60);

        X14Y5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X14Y5);
        X14Y5.setBounds(807, 248, 60, 60);

        X14Y6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X14Y6);
        X14Y6.setBounds(807, 310, 60, 60);

        X14Y7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X14Y7);
        X14Y7.setBounds(807, 372, 60, 60);

        X14Y8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X14Y8);
        X14Y8.setBounds(807, 434, 60, 60);

        X14Y9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X14Y9);
        X14Y9.setBounds(807, 497, 60, 60);

        X14Y10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X14Y10);
        X14Y10.setBounds(807, 558, 60, 60);

        X14Y11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X14Y11);
        X14Y11.setBounds(807, 620, 60, 60);

        X14Y12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X14Y12);
        X14Y12.setBounds(807, 682, 60, 60);

        X14Y13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TAmarillo.png"))); // NOI18N
        jPanel2.add(X14Y13);
        X14Y13.setBounds(807, 744, 60, 60);

        X14Y14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X14Y14);
        X14Y14.setBounds(807, 807, 60, 60);

        X14Y15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X14Y15);
        X14Y15.setBounds(807, 869, 60, 60);

        X15Y1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        X15Y1.setToolTipText("15,1");
        jPanel2.add(X15Y1);
        X15Y1.setBounds(869, 0, 60, 60);

        X15Y2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X15Y2);
        X15Y2.setBounds(869, 62, 60, 60);

        X15Y3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X15Y3);
        X15Y3.setBounds(869, 124, 60, 60);

        X15Y4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X15Y4);
        X15Y4.setBounds(869, 186, 60, 60);

        X15Y5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X15Y5);
        X15Y5.setBounds(869, 248, 60, 60);

        X15Y6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X15Y6);
        X15Y6.setBounds(869, 310, 60, 60);

        X15Y7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X15Y7);
        X15Y7.setBounds(869, 372, 60, 60);

        X15Y8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X15Y8);
        X15Y8.setBounds(869, 434, 60, 60);

        X15Y9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X15Y9);
        X15Y9.setBounds(869, 497, 60, 60);

        X15Y10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X15Y10);
        X15Y10.setBounds(869, 558, 60, 60);

        X15Y11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X15Y11);
        X15Y11.setBounds(869, 620, 60, 60);

        X15Y12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X15Y12);
        X15Y12.setBounds(869, 682, 60, 60);

        X15Y13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TAmarillo.png"))); // NOI18N
        jPanel2.add(X15Y13);
        X15Y13.setBounds(869, 744, 60, 60);

        X15Y14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X15Y14);
        X15Y14.setBounds(869, 807, 60, 60);

        X15Y15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/TNull.png"))); // NOI18N
        jPanel2.add(X15Y15);
        X15Y15.setBounds(869, 869, 60, 60);

        jInternalFrame1.getContentPane().add(jPanel2);
        jPanel2.setBounds(38, 38, 930, 930);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/Tablero.png"))); // NOI18N
        jLabel2.setAutoscrolls(true);
        jInternalFrame1.getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1000, 1000);
        jLabel2.getAccessibleContext().setAccessibleName("Tablero");

        jScrollPane2.setViewportView(jInternalFrame1);

        PanelTablero.add(jScrollPane2);
        jScrollPane2.setBounds(0, -30, 540, 540);

        getContentPane().add(PanelTablero);
        PanelTablero.setBounds(20, 20, 540, 510);

        NextPlayer3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/PNJ3.png"))); // NOI18N
        NextPlayer3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        NextPlayer3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 3));
        NextPlayer3.setFocusable(false);
        getContentPane().add(NextPlayer3);
        NextPlayer3.setBounds(580, 370, 100, 100);

        NextNick3.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        NextNick3.setForeground(new java.awt.Color(255, 255, 255));
        NextNick3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NextNick3.setText("Tea");
        NextNick3.setFocusable(false);
        getContentPane().add(NextNick3);
        NextNick3.setBounds(580, 350, 100, 20);

        jProgressBar3.setValue(76);
        jProgressBar3.setFocusable(false);
        getContentPane().add(jProgressBar3);
        jProgressBar3.setBounds(580, 470, 100, 14);

        NextPlayer2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/PNJ7.png"))); // NOI18N
        NextPlayer2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        NextPlayer2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));
        NextPlayer2.setFocusable(false);
        getContentPane().add(NextPlayer2);
        NextPlayer2.setBounds(580, 210, 100, 100);

        NextNick2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        NextNick2.setForeground(new java.awt.Color(255, 255, 255));
        NextNick2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NextNick2.setText("Duke");
        NextNick2.setFocusable(false);
        getContentPane().add(NextNick2);
        NextNick2.setBounds(580, 190, 100, 20);

        jProgressBar2.setValue(98);
        jProgressBar2.setFocusable(false);
        getContentPane().add(jProgressBar2);
        jProgressBar2.setBounds(580, 310, 100, 14);

        NextPlayer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 4.png"))); // NOI18N
        NextPlayer1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        NextPlayer1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 3));
        NextPlayer1.setFocusable(false);
        getContentPane().add(NextPlayer1);
        NextPlayer1.setBounds(580, 50, 100, 100);

        NextNick1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        NextNick1.setForeground(new java.awt.Color(255, 255, 255));
        NextNick1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NextNick1.setText("Usuario2");
        NextNick1.setFocusable(false);
        getContentPane().add(NextNick1);
        NextNick1.setBounds(580, 30, 100, 20);

        jProgressBar1.setValue(32);
        jProgressBar1.setFocusable(false);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(580, 150, 100, 14);

        PlayingPNG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 7.png"))); // NOI18N
        PlayingPNG.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PlayingPNG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 3));
        PlayingPNG.setFocusable(false);
        getContentPane().add(PlayingPNG);
        PlayingPNG.setBounds(20, 530, 100, 100);

        PlayingNick.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        PlayingNick.setForeground(new java.awt.Color(255, 255, 255));
        PlayingNick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PlayingNick.setText("Usuario");
        PlayingNick.setFocusable(false);
        getContentPane().add(PlayingNick);
        PlayingNick.setBounds(20, 630, 100, 20);

        PlayingVida.setBackground(new java.awt.Color(255, 0, 0));
        PlayingVida.setForeground(new java.awt.Color(0, 255, 0));
        PlayingVida.setMaximum(400);
        PlayingVida.setValue(345);
        PlayingVida.setBorderPainted(false);
        PlayingVida.setFocusable(false);
        PlayingVida.setString("");
        PlayingVida.setStringPainted(true);
        getContentPane().add(PlayingVida);
        PlayingVida.setBounds(20, 650, 640, 17);

        PanelAcciones.setOpaque(false);
        PanelAcciones.setLayout(null);

        BotonDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ETC/IconDice.png"))); // NOI18N
        BotonDados.setContentAreaFilled(false);
        BotonDados.setFocusable(false);
        BotonDados.setPreferredSize(new java.awt.Dimension(50, 50));
        PanelAcciones.add(BotonDados);
        BotonDados.setBounds(30, 9, 50, 50);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ETC/IconAttack.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusable(false);
        PanelAcciones.add(jButton1);
        jButton1.setBounds(95, 5, 60, 59);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ETC/IconMagic.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusable(false);
        PanelAcciones.add(jButton2);
        jButton2.setBounds(186, 5, 60, 59);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ETC/IconMove.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusable(false);
        PanelAcciones.add(jButton3);
        jButton3.setBounds(274, 5, 60, 59);

        JBInvocar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ETC/IconSummon.png"))); // NOI18N
        JBInvocar.setContentAreaFilled(false);
        JBInvocar.setFocusable(false);
        PanelAcciones.add(JBInvocar);
        JBInvocar.setBounds(352, 5, 70, 59);

        JBTrampa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ETC/IconTrap.png"))); // NOI18N
        JBTrampa.setContentAreaFilled(false);
        JBTrampa.setFocusable(false);
        PanelAcciones.add(JBTrampa);
        JBTrampa.setBounds(450, 5, 60, 59);

        JLdadosN5.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        JLdadosN5.setForeground(new java.awt.Color(255, 255, 255));
        JLdadosN5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLdadosN5.setText("2");
        JLdadosN5.setFocusable(false);
        PanelAcciones.add(JLdadosN5);
        JLdadosN5.setBounds(440, 80, 70, 30);

        JLdadosN4.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        JLdadosN4.setForeground(new java.awt.Color(255, 255, 255));
        JLdadosN4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLdadosN4.setText("0");
        JLdadosN4.setFocusable(false);
        PanelAcciones.add(JLdadosN4);
        JLdadosN4.setBounds(350, 80, 80, 30);

        JLdadosN3.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        JLdadosN3.setForeground(new java.awt.Color(255, 255, 255));
        JLdadosN3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLdadosN3.setText("0");
        JLdadosN3.setFocusable(false);
        PanelAcciones.add(JLdadosN3);
        JLdadosN3.setBounds(270, 80, 60, 30);

        JLdadosN2.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        JLdadosN2.setForeground(new java.awt.Color(255, 255, 255));
        JLdadosN2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLdadosN2.setText("3");
        JLdadosN2.setFocusable(false);
        PanelAcciones.add(JLdadosN2);
        JLdadosN2.setBounds(180, 80, 70, 30);

        JLDados.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        JLDados.setForeground(new java.awt.Color(255, 255, 255));
        JLDados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLDados.setText("Dados");
        JLDados.setFocusable(false);
        PanelAcciones.add(JLDados);
        JLDados.setBounds(10, 60, 83, 30);

        JLDadosN.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        JLDadosN.setForeground(new java.awt.Color(255, 255, 255));
        JLDadosN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLDadosN.setText("4");
        JLDadosN.setFocusable(false);
        PanelAcciones.add(JLDadosN);
        JLDadosN.setBounds(20, 80, 60, 30);

        JLAtacar.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        JLAtacar.setForeground(new java.awt.Color(255, 255, 255));
        JLAtacar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLAtacar.setText("Atacar");
        JLAtacar.setFocusable(false);
        PanelAcciones.add(JLAtacar);
        JLAtacar.setBounds(90, 60, 70, 30);

        JLAtacarN.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        JLAtacarN.setForeground(new java.awt.Color(255, 255, 255));
        JLAtacarN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLAtacarN.setText("1");
        JLAtacarN.setFocusable(false);
        PanelAcciones.add(JLAtacarN);
        JLAtacarN.setBounds(90, 80, 70, 30);

        JLMagia.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        JLMagia.setForeground(new java.awt.Color(255, 255, 255));
        JLMagia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLMagia.setText("Magia");
        JLMagia.setFocusable(false);
        PanelAcciones.add(JLMagia);
        JLMagia.setBounds(180, 60, 70, 30);

        JLMover.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        JLMover.setForeground(new java.awt.Color(255, 255, 255));
        JLMover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLMover.setText("Mover");
        JLMover.setFocusable(false);
        PanelAcciones.add(JLMover);
        JLMover.setBounds(273, 60, 60, 30);

        JLTrampa.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        JLTrampa.setForeground(new java.awt.Color(255, 255, 255));
        JLTrampa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLTrampa.setText("Trampa");
        JLTrampa.setFocusable(false);
        PanelAcciones.add(JLTrampa);
        JLTrampa.setBounds(443, 60, 70, 30);

        JLInvocar.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        JLInvocar.setForeground(new java.awt.Color(255, 255, 255));
        JLInvocar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLInvocar.setText("Invocar");
        JLInvocar.setFocusable(false);
        PanelAcciones.add(JLInvocar);
        JLInvocar.setBounds(353, 60, 70, 30);

        FondoAcciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/BGBlack.png"))); // NOI18N
        FondoAcciones.setFocusable(false);
        PanelAcciones.add(FondoAcciones);
        FondoAcciones.setBounds(0, 0, 550, 120);

        getContentPane().add(PanelAcciones);
        PanelAcciones.setBounds(120, 530, 550, 120);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/Fondo.png"))); // NOI18N
        Fondo.setFocusable(false);
        getContentPane().add(Fondo);
        Fondo.setBounds(0, 0, 700, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonDados;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel FondoAcciones;
    private javax.swing.JButton JBInvocar;
    private javax.swing.JButton JBTrampa;
    private javax.swing.JLabel JLAtacar;
    private javax.swing.JLabel JLAtacarN;
    private javax.swing.JLabel JLDados;
    private javax.swing.JLabel JLDadosN;
    private javax.swing.JLabel JLInvocar;
    private javax.swing.JLabel JLMagia;
    private javax.swing.JLabel JLMover;
    private javax.swing.JLabel JLTrampa;
    private javax.swing.JLabel JLdadosN2;
    private javax.swing.JLabel JLdadosN3;
    private javax.swing.JLabel JLdadosN4;
    private javax.swing.JLabel JLdadosN5;
    private javax.swing.JLabel NextNick1;
    private javax.swing.JLabel NextNick2;
    private javax.swing.JLabel NextNick3;
    private javax.swing.JLabel NextPlayer1;
    private javax.swing.JLabel NextPlayer2;
    private javax.swing.JLabel NextPlayer3;
    private javax.swing.JPanel PanelAcciones;
    private javax.swing.JPanel PanelTablero;
    private javax.swing.JLabel PlayingNick;
    private javax.swing.JLabel PlayingPNG;
    private javax.swing.JProgressBar PlayingVida;
    private javax.swing.JLabel X10Y1;
    private javax.swing.JLabel X10Y10;
    private javax.swing.JLabel X10Y11;
    private javax.swing.JLabel X10Y12;
    private javax.swing.JLabel X10Y13;
    private javax.swing.JLabel X10Y14;
    private javax.swing.JLabel X10Y15;
    private javax.swing.JLabel X10Y2;
    private javax.swing.JLabel X10Y3;
    private javax.swing.JLabel X10Y4;
    private javax.swing.JLabel X10Y5;
    private javax.swing.JLabel X10Y6;
    private javax.swing.JLabel X10Y7;
    private javax.swing.JLabel X10Y8;
    private javax.swing.JLabel X10Y9;
    private javax.swing.JLabel X11Y1;
    private javax.swing.JLabel X11Y10;
    private javax.swing.JLabel X11Y11;
    private javax.swing.JLabel X11Y12;
    private javax.swing.JLabel X11Y13;
    private javax.swing.JLabel X11Y14;
    private javax.swing.JLabel X11Y15;
    private javax.swing.JLabel X11Y2;
    private javax.swing.JLabel X11Y3;
    private javax.swing.JLabel X11Y4;
    private javax.swing.JLabel X11Y5;
    private javax.swing.JLabel X11Y6;
    private javax.swing.JLabel X11Y7;
    private javax.swing.JLabel X11Y8;
    private javax.swing.JLabel X11Y9;
    private javax.swing.JLabel X12Y1;
    private javax.swing.JLabel X12Y10;
    private javax.swing.JLabel X12Y11;
    private javax.swing.JLabel X12Y12;
    private javax.swing.JLabel X12Y13;
    private javax.swing.JLabel X12Y14;
    private javax.swing.JLabel X12Y15;
    private javax.swing.JLabel X12Y2;
    private javax.swing.JLabel X12Y3;
    private javax.swing.JLabel X12Y4;
    private javax.swing.JLabel X12Y5;
    private javax.swing.JLabel X12Y6;
    private javax.swing.JLabel X12Y7;
    private javax.swing.JLabel X12Y8;
    private javax.swing.JLabel X12Y9;
    private javax.swing.JLabel X13Y1;
    private javax.swing.JLabel X13Y10;
    private javax.swing.JLabel X13Y11;
    private javax.swing.JLabel X13Y12;
    private javax.swing.JLabel X13Y13;
    private javax.swing.JLabel X13Y14;
    private javax.swing.JLabel X13Y15;
    private javax.swing.JLabel X13Y2;
    private javax.swing.JLabel X13Y3;
    private javax.swing.JLabel X13Y4;
    private javax.swing.JLabel X13Y5;
    private javax.swing.JLabel X13Y6;
    private javax.swing.JLabel X13Y7;
    private javax.swing.JLabel X13Y8;
    private javax.swing.JLabel X13Y9;
    private javax.swing.JLabel X14Y1;
    private javax.swing.JLabel X14Y10;
    private javax.swing.JLabel X14Y11;
    private javax.swing.JLabel X14Y12;
    private javax.swing.JLabel X14Y13;
    private javax.swing.JLabel X14Y14;
    private javax.swing.JLabel X14Y15;
    private javax.swing.JLabel X14Y2;
    private javax.swing.JLabel X14Y3;
    private javax.swing.JLabel X14Y4;
    private javax.swing.JLabel X14Y5;
    private javax.swing.JLabel X14Y6;
    private javax.swing.JLabel X14Y7;
    private javax.swing.JLabel X14Y8;
    private javax.swing.JLabel X14Y9;
    private javax.swing.JLabel X15Y1;
    private javax.swing.JLabel X15Y10;
    private javax.swing.JLabel X15Y11;
    private javax.swing.JLabel X15Y12;
    private javax.swing.JLabel X15Y13;
    private javax.swing.JLabel X15Y14;
    private javax.swing.JLabel X15Y15;
    private javax.swing.JLabel X15Y2;
    private javax.swing.JLabel X15Y3;
    private javax.swing.JLabel X15Y4;
    private javax.swing.JLabel X15Y5;
    private javax.swing.JLabel X15Y6;
    private javax.swing.JLabel X15Y7;
    private javax.swing.JLabel X15Y8;
    private javax.swing.JLabel X15Y9;
    private javax.swing.JLabel X1Y1;
    private javax.swing.JLabel X1Y10;
    private javax.swing.JLabel X1Y11;
    private javax.swing.JLabel X1Y12;
    private javax.swing.JLabel X1Y13;
    private javax.swing.JLabel X1Y14;
    private javax.swing.JLabel X1Y15;
    private javax.swing.JLabel X1Y2;
    private javax.swing.JLabel X1Y3;
    private javax.swing.JLabel X1Y4;
    private javax.swing.JLabel X1Y5;
    private javax.swing.JLabel X1Y6;
    private javax.swing.JLabel X1Y7;
    private javax.swing.JLabel X1Y8;
    private javax.swing.JLabel X1Y9;
    private javax.swing.JLabel X2Y1;
    private javax.swing.JLabel X2Y10;
    private javax.swing.JLabel X2Y11;
    private javax.swing.JLabel X2Y12;
    private javax.swing.JLabel X2Y13;
    private javax.swing.JLabel X2Y14;
    private javax.swing.JLabel X2Y15;
    private javax.swing.JLabel X2Y2;
    private javax.swing.JLabel X2Y3;
    private javax.swing.JLabel X2Y4;
    private javax.swing.JLabel X2Y5;
    private javax.swing.JLabel X2Y6;
    private javax.swing.JLabel X2Y7;
    private javax.swing.JLabel X2Y8;
    private javax.swing.JLabel X2Y9;
    private javax.swing.JLabel X3Y1;
    private javax.swing.JLabel X3Y10;
    private javax.swing.JLabel X3Y11;
    private javax.swing.JLabel X3Y12;
    private javax.swing.JLabel X3Y13;
    private javax.swing.JLabel X3Y14;
    private javax.swing.JLabel X3Y15;
    private javax.swing.JLabel X3Y2;
    private javax.swing.JLabel X3Y3;
    private javax.swing.JLabel X3Y4;
    private javax.swing.JLabel X3Y5;
    private javax.swing.JLabel X3Y6;
    private javax.swing.JLabel X3Y7;
    private javax.swing.JLabel X3Y8;
    private javax.swing.JLabel X3Y9;
    private javax.swing.JLabel X4Y1;
    private javax.swing.JLabel X4Y10;
    private javax.swing.JLabel X4Y11;
    private javax.swing.JLabel X4Y12;
    private javax.swing.JLabel X4Y13;
    private javax.swing.JLabel X4Y14;
    private javax.swing.JLabel X4Y15;
    private javax.swing.JLabel X4Y2;
    private javax.swing.JLabel X4Y3;
    private javax.swing.JLabel X4Y4;
    private javax.swing.JLabel X4Y5;
    private javax.swing.JLabel X4Y6;
    private javax.swing.JLabel X4Y7;
    private javax.swing.JLabel X4Y8;
    private javax.swing.JLabel X4Y9;
    private javax.swing.JLabel X5Y1;
    private javax.swing.JLabel X5Y10;
    private javax.swing.JLabel X5Y11;
    private javax.swing.JLabel X5Y12;
    private javax.swing.JLabel X5Y13;
    private javax.swing.JLabel X5Y14;
    private javax.swing.JLabel X5Y15;
    private javax.swing.JLabel X5Y2;
    private javax.swing.JLabel X5Y3;
    private javax.swing.JLabel X5Y4;
    private javax.swing.JLabel X5Y5;
    private javax.swing.JLabel X5Y6;
    private javax.swing.JLabel X5Y7;
    private javax.swing.JLabel X5Y8;
    private javax.swing.JLabel X5Y9;
    private javax.swing.JLabel X6Y1;
    private javax.swing.JLabel X6Y10;
    private javax.swing.JLabel X6Y11;
    private javax.swing.JLabel X6Y12;
    private javax.swing.JLabel X6Y13;
    private javax.swing.JLabel X6Y14;
    private javax.swing.JLabel X6Y15;
    private javax.swing.JLabel X6Y2;
    private javax.swing.JLabel X6Y3;
    private javax.swing.JLabel X6Y4;
    private javax.swing.JLabel X6Y5;
    private javax.swing.JLabel X6Y6;
    private javax.swing.JLabel X6Y7;
    private javax.swing.JLabel X6Y8;
    private javax.swing.JLabel X6Y9;
    private javax.swing.JLabel X7Y1;
    private javax.swing.JLabel X7Y10;
    private javax.swing.JLabel X7Y11;
    private javax.swing.JLabel X7Y12;
    private javax.swing.JLabel X7Y13;
    private javax.swing.JLabel X7Y14;
    private javax.swing.JLabel X7Y15;
    private javax.swing.JLabel X7Y2;
    private javax.swing.JLabel X7Y3;
    private javax.swing.JLabel X7Y4;
    private javax.swing.JLabel X7Y5;
    private javax.swing.JLabel X7Y6;
    private javax.swing.JLabel X7Y7;
    private javax.swing.JLabel X7Y8;
    private javax.swing.JLabel X7Y9;
    private javax.swing.JLabel X8Y1;
    private javax.swing.JLabel X8Y10;
    private javax.swing.JLabel X8Y11;
    private javax.swing.JLabel X8Y12;
    private javax.swing.JLabel X8Y13;
    private javax.swing.JLabel X8Y14;
    private javax.swing.JLabel X8Y15;
    private javax.swing.JLabel X8Y2;
    private javax.swing.JLabel X8Y3;
    private javax.swing.JLabel X8Y4;
    private javax.swing.JLabel X8Y5;
    private javax.swing.JLabel X8Y6;
    private javax.swing.JLabel X8Y7;
    private javax.swing.JLabel X8Y8;
    private javax.swing.JLabel X8Y9;
    private javax.swing.JLabel X9Y1;
    private javax.swing.JLabel X9Y10;
    private javax.swing.JLabel X9Y11;
    private javax.swing.JLabel X9Y12;
    private javax.swing.JLabel X9Y13;
    private javax.swing.JLabel X9Y14;
    private javax.swing.JLabel X9Y15;
    private javax.swing.JLabel X9Y2;
    private javax.swing.JLabel X9Y3;
    private javax.swing.JLabel X9Y4;
    private javax.swing.JLabel X9Y5;
    private javax.swing.JLabel X9Y6;
    private javax.swing.JLabel X9Y7;
    private javax.swing.JLabel X9Y8;
    private javax.swing.JLabel X9Y9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
