package Vistas;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JButton;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Username = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        BotonIngresar = new javax.swing.JButton();
        BotonRegistrarse = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        Username.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        Username.setToolTipText("Usuario");
        Username.setAlignmentY(4.0F);
        getContentPane().add(Username);
        Username.setBounds(460, 380, 200, 40);

        Password.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        Password.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Password.setToolTipText("Contraseña");
        getContentPane().add(Password);
        Password.setBounds(460, 430, 200, 40);

        BotonIngresar.setBackground(new java.awt.Color(255, 255, 255));
        BotonIngresar.setForeground(new java.awt.Color(255, 255, 255));
        BotonIngresar.setToolTipText("Ingresar");
        BotonIngresar.setBorderPainted(false);
        BotonIngresar.setContentAreaFilled(false);
        getContentPane().add(BotonIngresar);
        BotonIngresar.setBounds(520, 480, 150, 60);

        BotonRegistrarse.setFont(new java.awt.Font("Consolas", 1, 28)); // NOI18N
        BotonRegistrarse.setForeground(new java.awt.Color(51, 255, 0));
        BotonRegistrarse.setText("REGISTRATE");
        BotonRegistrarse.setToolTipText("Registrarse");
        BotonRegistrarse.setBorder(null);
        BotonRegistrarse.setBorderPainted(false);
        BotonRegistrarse.setContentAreaFilled(false);
        BotonRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(BotonRegistrarse);
        BotonRegistrarse.setBounds(364, 512, 150, 30);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/Login.png"))); // NOI18N
        Fondo.setToolTipText("");
        getContentPane().add(Fondo);
        Fondo.setBounds(0, 0, 700, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBotonIngresar() {
        return BotonIngresar;
    }
public String getnombre(){
        return this.Username.getText();
    }

    public String getpassword(){
        return String.valueOf(this.Password.getPassword());
    }
    
    public JButton getBotonRegistrarse() {
        return BotonRegistrarse;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonIngresar;
    private javax.swing.JButton BotonRegistrarse;
    private javax.swing.JLabel Fondo;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField Username;
    // End of variables declaration//GEN-END:variables

 

   
}
