/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Eric Ramirez Santis
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setLocationRelativeTo( null );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBEditarPuzzle = new javax.swing.JButton();
        JBPartidaLibre = new javax.swing.JButton();
        JBTorneo = new javax.swing.JButton();
        JBVerPerfil = new javax.swing.JButton();
        JBConfiguraciones = new javax.swing.JButton();
        JBCerrarSesion = new javax.swing.JButton();
        JLBienvenido = new javax.swing.JLabel();
        JLUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        JBEditarPuzzle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ETC/BMM1.png"))); // NOI18N
        JBEditarPuzzle.setBorderPainted(false);
        JBEditarPuzzle.setContentAreaFilled(false);
        JBEditarPuzzle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(JBEditarPuzzle);
        JBEditarPuzzle.setBounds(30, 90, 220, 60);

        JBPartidaLibre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ETC/BMM2.png"))); // NOI18N
        JBPartidaLibre.setBorderPainted(false);
        JBPartidaLibre.setContentAreaFilled(false);
        getContentPane().add(JBPartidaLibre);
        JBPartidaLibre.setBounds(50, 150, 220, 60);

        JBTorneo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ETC/BMM3.png"))); // NOI18N
        JBTorneo.setBorderPainted(false);
        JBTorneo.setContentAreaFilled(false);
        getContentPane().add(JBTorneo);
        JBTorneo.setBounds(70, 210, 220, 60);

        JBVerPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ETC/BMM4.png"))); // NOI18N
        JBVerPerfil.setBorderPainted(false);
        JBVerPerfil.setContentAreaFilled(false);
        getContentPane().add(JBVerPerfil);
        JBVerPerfil.setBounds(90, 270, 220, 60);

        JBConfiguraciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ETC/BMM5.png"))); // NOI18N
        JBConfiguraciones.setBorderPainted(false);
        JBConfiguraciones.setContentAreaFilled(false);
        getContentPane().add(JBConfiguraciones);
        JBConfiguraciones.setBounds(110, 330, 220, 60);

        JBCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ETC/BMM6.png"))); // NOI18N
        JBCerrarSesion.setBorderPainted(false);
        JBCerrarSesion.setContentAreaFilled(false);
        getContentPane().add(JBCerrarSesion);
        JBCerrarSesion.setBounds(130, 390, 220, 60);

        JLBienvenido.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        JLBienvenido.setForeground(new java.awt.Color(255, 255, 255));
        JLBienvenido.setText("Bienvenido(a)");
        getContentPane().add(JLBienvenido);
        JLBienvenido.setBounds(10, 10, 150, 50);

        JLUsuario.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        JLUsuario.setForeground(new java.awt.Color(255, 255, 255));
        JLUsuario.setText("NombreDeUsuario");
        getContentPane().add(JLUsuario);
        JLUsuario.setBounds(150, 10, 350, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/FondoMM.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBCerrarSesion;
    private javax.swing.JButton JBConfiguraciones;
    private javax.swing.JButton JBEditarPuzzle;
    private javax.swing.JButton JBPartidaLibre;
    private javax.swing.JButton JBTorneo;
    private javax.swing.JButton JBVerPerfil;
    private javax.swing.JLabel JLBienvenido;
    private javax.swing.JLabel JLUsuario;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
