/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Eric Ramirez Santis
 */
public class SeleccionAvatar extends javax.swing.JFrame {

    /**
     * Creates new form SeleccionAvatar
     */
    public SeleccionAvatar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jToggleButton17 = new javax.swing.JToggleButton();
        jToggleButton18 = new javax.swing.JToggleButton();
        jToggleButton19 = new javax.swing.JToggleButton();
        jToggleButton20 = new javax.swing.JToggleButton();
        jToggleButton21 = new javax.swing.JToggleButton();
        jToggleButton22 = new javax.swing.JToggleButton();
        jToggleButton23 = new javax.swing.JToggleButton();
        jToggleButton24 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setOpaque(false);

        buttonGroup1.add(jToggleButton1);
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 1.png"))); // NOI18N
        jToggleButton1.setSelected(true);
        jToggleButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton1.setContentAreaFilled(false);
        jToggleButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jToggleButton1.setFocusPainted(false);
        jToggleButton1.setName(""); // NOI18N
        jToggleButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 1 S.png"))); // NOI18N
        jPanel1.add(jToggleButton1);

        buttonGroup1.add(jToggleButton2);
        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 2.png"))); // NOI18N
        jToggleButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton2.setContentAreaFilled(false);
        jToggleButton2.setFocusPainted(false);
        jToggleButton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 2 S.png"))); // NOI18N
        jPanel1.add(jToggleButton2);

        buttonGroup1.add(jToggleButton3);
        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 3.png"))); // NOI18N
        jToggleButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton3.setContentAreaFilled(false);
        jToggleButton3.setFocusable(false);
        jToggleButton3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 3 S.png"))); // NOI18N
        jPanel1.add(jToggleButton3);

        buttonGroup1.add(jToggleButton4);
        jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 4.png"))); // NOI18N
        jToggleButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton4.setContentAreaFilled(false);
        jToggleButton4.setFocusable(false);
        jToggleButton4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 4 S.png"))); // NOI18N
        jPanel1.add(jToggleButton4);

        buttonGroup1.add(jToggleButton5);
        jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 5.png"))); // NOI18N
        jToggleButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton5.setContentAreaFilled(false);
        jToggleButton5.setFocusable(false);
        jToggleButton5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 5 S.png"))); // NOI18N
        jPanel1.add(jToggleButton5);

        buttonGroup1.add(jToggleButton6);
        jToggleButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 6.png"))); // NOI18N
        jToggleButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton6.setContentAreaFilled(false);
        jToggleButton6.setFocusPainted(false);
        jToggleButton6.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 6 S.png"))); // NOI18N
        jPanel1.add(jToggleButton6);

        buttonGroup1.add(jToggleButton7);
        jToggleButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 7.png"))); // NOI18N
        jToggleButton7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton7.setContentAreaFilled(false);
        jToggleButton7.setFocusPainted(false);
        jToggleButton7.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 7 S.png"))); // NOI18N
        jPanel1.add(jToggleButton7);

        buttonGroup1.add(jToggleButton8);
        jToggleButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 8.png"))); // NOI18N
        jToggleButton8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton8.setContentAreaFilled(false);
        jToggleButton8.setFocusPainted(false);
        jToggleButton8.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 8 S.png"))); // NOI18N
        jPanel1.add(jToggleButton8);

        buttonGroup1.add(jToggleButton9);
        jToggleButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 9.png"))); // NOI18N
        jToggleButton9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton9.setContentAreaFilled(false);
        jToggleButton9.setFocusPainted(false);
        jToggleButton9.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 9 S.png"))); // NOI18N
        jPanel1.add(jToggleButton9);

        buttonGroup1.add(jToggleButton10);
        jToggleButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 10.png"))); // NOI18N
        jToggleButton10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton10.setContentAreaFilled(false);
        jToggleButton10.setFocusPainted(false);
        jToggleButton10.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 10 S.png"))); // NOI18N
        jPanel1.add(jToggleButton10);

        buttonGroup1.add(jToggleButton11);
        jToggleButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 11.png"))); // NOI18N
        jToggleButton11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton11.setContentAreaFilled(false);
        jToggleButton11.setFocusPainted(false);
        jToggleButton11.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 11 S.png"))); // NOI18N
        jPanel1.add(jToggleButton11);

        buttonGroup1.add(jToggleButton12);
        jToggleButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 12.png"))); // NOI18N
        jToggleButton12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton12.setContentAreaFilled(false);
        jToggleButton12.setFocusPainted(false);
        jToggleButton12.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 12 S.png"))); // NOI18N
        jPanel1.add(jToggleButton12);

        buttonGroup1.add(jToggleButton13);
        jToggleButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 13.png"))); // NOI18N
        jToggleButton13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton13.setContentAreaFilled(false);
        jToggleButton13.setFocusPainted(false);
        jToggleButton13.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 13 S.png"))); // NOI18N
        jPanel1.add(jToggleButton13);

        buttonGroup1.add(jToggleButton14);
        jToggleButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 14.png"))); // NOI18N
        jToggleButton14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton14.setContentAreaFilled(false);
        jToggleButton14.setFocusPainted(false);
        jToggleButton14.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 14 S.png"))); // NOI18N
        jPanel1.add(jToggleButton14);

        buttonGroup1.add(jToggleButton15);
        jToggleButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 15.png"))); // NOI18N
        jToggleButton15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton15.setContentAreaFilled(false);
        jToggleButton15.setFocusPainted(false);
        jToggleButton15.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 15 S.png"))); // NOI18N
        jPanel1.add(jToggleButton15);

        buttonGroup1.add(jToggleButton16);
        jToggleButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 16.png"))); // NOI18N
        jToggleButton16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton16.setContentAreaFilled(false);
        jToggleButton16.setFocusPainted(false);
        jToggleButton16.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 16 S.png"))); // NOI18N
        jPanel1.add(jToggleButton16);

        buttonGroup1.add(jToggleButton17);
        jToggleButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 17.png"))); // NOI18N
        jToggleButton17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton17.setContentAreaFilled(false);
        jToggleButton17.setFocusPainted(false);
        jToggleButton17.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 17 S.png"))); // NOI18N
        jPanel1.add(jToggleButton17);

        buttonGroup1.add(jToggleButton18);
        jToggleButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 18.png"))); // NOI18N
        jToggleButton18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton18.setContentAreaFilled(false);
        jToggleButton18.setFocusPainted(false);
        jToggleButton18.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 18 S.png"))); // NOI18N
        jPanel1.add(jToggleButton18);

        buttonGroup1.add(jToggleButton19);
        jToggleButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 19.png"))); // NOI18N
        jToggleButton19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton19.setContentAreaFilled(false);
        jToggleButton19.setFocusPainted(false);
        jToggleButton19.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 19 S.png"))); // NOI18N
        jToggleButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton19ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton19);

        buttonGroup1.add(jToggleButton20);
        jToggleButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 20.png"))); // NOI18N
        jToggleButton20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton20.setContentAreaFilled(false);
        jToggleButton20.setFocusPainted(false);
        jToggleButton20.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 20 S.png"))); // NOI18N
        jPanel1.add(jToggleButton20);

        buttonGroup1.add(jToggleButton21);
        jToggleButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 21.png"))); // NOI18N
        jToggleButton21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton21.setContentAreaFilled(false);
        jToggleButton21.setFocusPainted(false);
        jToggleButton21.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 21 S.png"))); // NOI18N
        jPanel1.add(jToggleButton21);

        buttonGroup1.add(jToggleButton22);
        jToggleButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 22.png"))); // NOI18N
        jToggleButton22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton22.setContentAreaFilled(false);
        jToggleButton22.setFocusPainted(false);
        jToggleButton22.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 22 S.png"))); // NOI18N
        jPanel1.add(jToggleButton22);

        buttonGroup1.add(jToggleButton23);
        jToggleButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 23.png"))); // NOI18N
        jToggleButton23.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton23.setContentAreaFilled(false);
        jToggleButton23.setFocusPainted(false);
        jToggleButton23.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 23 S.png"))); // NOI18N
        jPanel1.add(jToggleButton23);

        buttonGroup1.add(jToggleButton24);
        jToggleButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 24.png"))); // NOI18N
        jToggleButton24.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton24.setContentAreaFilled(false);
        jToggleButton24.setFocusPainted(false);
        jToggleButton24.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caras/Cara 24 S.png"))); // NOI18N
        jPanel1.add(jToggleButton24);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 170, 700, 430);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ETC/confirmar.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        getContentPane().add(jButton1);
        jButton1.setBounds(520, 590, 150, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/Seleccion Avatar.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton19ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JToggleButton jToggleButton19;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton20;
    private javax.swing.JToggleButton jToggleButton21;
    private javax.swing.JToggleButton jToggleButton22;
    private javax.swing.JToggleButton jToggleButton23;
    private javax.swing.JToggleButton jToggleButton24;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    // End of variables declaration//GEN-END:variables
}
