/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.ControladorSeleccionJefeTerreno;

/**
 *
 * @author Eric Ramirez Santis
 */
public class VistaSeleccionJefeTerreno extends javax.swing.JFrame {

    /**
     * Creates new form SeleccionJefeTerreno
     */
    public VistaSeleccionJefeTerreno() {
        initComponents();
        Grupo1.add(RB1);
        Grupo1.add(RB2);
        Grupo1.add(RB3);
        Grupo1.add(RB4);
        Grupo1.add(RB5);
        Grupo1.add(RB6);
        Grupo1.add(RB7);
        Grupo1.add(RB8);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grupo1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        RB1 = new javax.swing.JRadioButton();
        RB2 = new javax.swing.JRadioButton();
        RB3 = new javax.swing.JRadioButton();
        RB4 = new javax.swing.JRadioButton();
        RB5 = new javax.swing.JRadioButton();
        RB6 = new javax.swing.JRadioButton();
        RB7 = new javax.swing.JRadioButton();
        RB8 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        PanelPotrait = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setOpaque(false);

        Grupo1.add(RB1);
        RB1.setFont(new java.awt.Font("Consolas", 0, 30)); // NOI18N
        RB1.setForeground(new java.awt.Color(255, 255, 255));
        RB1.setSelected(true);
        RB1.setText("Jefe 1");
        RB1.setContentAreaFilled(false);
        RB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RB1MouseClicked(evt);
            }
        });
        jPanel1.add(RB1);

        Grupo1.add(RB2);
        RB2.setFont(new java.awt.Font("Consolas", 0, 30)); // NOI18N
        RB2.setForeground(new java.awt.Color(255, 255, 255));
        RB2.setText("Jefe 2");
        RB2.setContentAreaFilled(false);
        RB2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RB2MouseClicked(evt);
            }
        });
        RB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB2ActionPerformed(evt);
            }
        });
        jPanel1.add(RB2);

        Grupo1.add(RB3);
        RB3.setFont(new java.awt.Font("Consolas", 0, 30)); // NOI18N
        RB3.setForeground(new java.awt.Color(255, 255, 255));
        RB3.setText("Jefe 3");
        RB3.setContentAreaFilled(false);
        RB3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RB3MouseClicked(evt);
            }
        });
        jPanel1.add(RB3);

        Grupo1.add(RB4);
        RB4.setFont(new java.awt.Font("Consolas", 0, 30)); // NOI18N
        RB4.setForeground(new java.awt.Color(255, 255, 255));
        RB4.setText("Jefe 4");
        RB4.setContentAreaFilled(false);
        RB4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RB4MouseClicked(evt);
            }
        });
        jPanel1.add(RB4);

        Grupo1.add(RB5);
        RB5.setFont(new java.awt.Font("Consolas", 0, 30)); // NOI18N
        RB5.setForeground(new java.awt.Color(255, 255, 255));
        RB5.setText("Jefe 5");
        RB5.setContentAreaFilled(false);
        RB5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RB5MouseClicked(evt);
            }
        });
        jPanel1.add(RB5);

        Grupo1.add(RB6);
        RB6.setFont(new java.awt.Font("Consolas", 0, 30)); // NOI18N
        RB6.setForeground(new java.awt.Color(255, 255, 255));
        RB6.setText("Jefe 6");
        RB6.setContentAreaFilled(false);
        RB6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RB6MouseClicked(evt);
            }
        });
        jPanel1.add(RB6);

        Grupo1.add(RB7);
        RB7.setFont(new java.awt.Font("Consolas", 0, 30)); // NOI18N
        RB7.setForeground(new java.awt.Color(255, 255, 255));
        RB7.setText("Jefe 7");
        RB7.setContentAreaFilled(false);
        RB7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RB7MouseClicked(evt);
            }
        });
        jPanel1.add(RB7);

        Grupo1.add(RB8);
        RB8.setFont(new java.awt.Font("Consolas", 0, 30)); // NOI18N
        RB8.setForeground(new java.awt.Color(255, 255, 255));
        RB8.setText("Jefe 8");
        RB8.setContentAreaFilled(false);
        RB8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RB8MouseClicked(evt);
            }
        });
        RB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB8ActionPerformed(evt);
            }
        });
        jPanel1.add(RB8);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 200, 200, 420);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Characters/Jefes/JEFE Angel.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setPreferredSize(new java.awt.Dimension(90, 64));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(480, 380, 80, 70);

        PanelPotrait.setAutoscrolls(true);
        PanelPotrait.setOpaque(false);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Potraits/Jefes/JEFE Angel.png"))); // NOI18N
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PanelPotrait.add(jLabel3);

        getContentPane().add(PanelPotrait);
        PanelPotrait.setBounds(350, 150, 340, 230);

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabel4.setText("JEFE 1");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(380, 470, 80, 30);

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabel5.setText("Clase");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(380, 500, 100, 20);

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabel6.setText("Habilidades");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(380, 530, 210, 30);

        jLabel7.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Descripción . . . . . . .");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(380, 560, 260, 100);
        getContentPane().add(jScrollBar1);
        jScrollBar1.setBounds(650, 470, 17, 180);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/Selección de Jefe de Terreno.png"))); // NOI18N
        jLabel1.setFocusable(false);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 700);

        jButton1.setText("jButton1");
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 610, 73, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB8ActionPerformed

    private void RB1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RB1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RB1MouseClicked

    private void RB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB2ActionPerformed

    private void RB2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RB2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RB2MouseClicked

    private void RB3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RB3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RB3MouseClicked

    private void RB4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RB4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RB4MouseClicked

    private void RB5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RB5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RB5MouseClicked

    private void RB6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RB6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RB6MouseClicked

    private void RB7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RB7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RB7MouseClicked

    private void RB8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RB8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RB8MouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.ButtonGroup Grupo1;
    private javax.swing.JPanel PanelPotrait;
    private javax.swing.JRadioButton RB1;
    private javax.swing.JRadioButton RB2;
    private javax.swing.JRadioButton RB3;
    private javax.swing.JRadioButton RB4;
    private javax.swing.JRadioButton RB5;
    private javax.swing.JRadioButton RB6;
    private javax.swing.JRadioButton RB7;
    private javax.swing.JRadioButton RB8;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    // End of variables declaration//GEN-END:variables

    public void agregarListener(ControladorSeleccionJefeTerreno aThis) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
