/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.Dimension;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Eric Ramirez Santis
 */
public class VistaMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public VistaMenuPrincipal() {
        initComponents();
        this.setMinimumSize(new Dimension (702, 702));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonPuzzleDados = new javax.swing.JButton();
        botonPartidaLibre = new javax.swing.JButton();
        botonTorneo = new javax.swing.JButton();
        botonVerPerfil = new javax.swing.JButton();
        botonConfiguraciones = new javax.swing.JButton();
        botonCerrarSesion = new javax.swing.JButton();
        JLBienvenido = new javax.swing.JLabel();
        JLUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        botonPuzzleDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ETC/BMM1.png"))); // NOI18N
        botonPuzzleDados.setBorderPainted(false);
        botonPuzzleDados.setContentAreaFilled(false);
        botonPuzzleDados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonPuzzleDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPuzzleDadosActionPerformed(evt);
            }
        });
        getContentPane().add(botonPuzzleDados);
        botonPuzzleDados.setBounds(240, 420, 220, 60);

        botonPartidaLibre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ETC/BMM2.png"))); // NOI18N
        botonPartidaLibre.setBorderPainted(false);
        botonPartidaLibre.setContentAreaFilled(false);
        getContentPane().add(botonPartidaLibre);
        botonPartidaLibre.setBounds(90, 250, 220, 60);

        botonTorneo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ETC/BMM3.png"))); // NOI18N
        botonTorneo.setBorderPainted(false);
        botonTorneo.setContentAreaFilled(false);
        getContentPane().add(botonTorneo);
        botonTorneo.setBounds(160, 340, 220, 60);

        botonVerPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ETC/BMM4.png"))); // NOI18N
        botonVerPerfil.setBorderPainted(false);
        botonVerPerfil.setContentAreaFilled(false);
        getContentPane().add(botonVerPerfil);
        botonVerPerfil.setBounds(30, 160, 220, 60);

        botonConfiguraciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ETC/BMM5.png"))); // NOI18N
        botonConfiguraciones.setBorderPainted(false);
        botonConfiguraciones.setContentAreaFilled(false);
        getContentPane().add(botonConfiguraciones);
        botonConfiguraciones.setBounds(330, 500, 220, 60);

        botonCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ETC/BMM6.png"))); // NOI18N
        botonCerrarSesion.setBorderPainted(false);
        botonCerrarSesion.setContentAreaFilled(false);
        getContentPane().add(botonCerrarSesion);
        botonCerrarSesion.setBounds(420, 570, 220, 60);

        JLBienvenido.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        JLBienvenido.setForeground(new java.awt.Color(255, 255, 255));
        JLBienvenido.setText("Bienvenido(a)");
        getContentPane().add(JLBienvenido);
        JLBienvenido.setBounds(10, 50, 150, 50);

        JLUsuario.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        JLUsuario.setForeground(new java.awt.Color(255, 255, 255));
        JLUsuario.setText("NombreDeUsuario");
        getContentPane().add(JLUsuario);
        JLUsuario.setBounds(150, 50, 350, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/FondoMM.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPuzzleDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPuzzleDadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonPuzzleDadosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLBienvenido;
    private javax.swing.JLabel JLUsuario;
    private javax.swing.JButton botonCerrarSesion;
    private javax.swing.JButton botonConfiguraciones;
    private javax.swing.JButton botonPartidaLibre;
    private javax.swing.JButton botonPuzzleDados;
    private javax.swing.JButton botonTorneo;
    private javax.swing.JButton botonVerPerfil;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
//Método que hará que otra clase escuche lo que está sucediendo en esta vista
    public void agregarListener(ActionListener al)
    {
        this.botonCerrarSesion.addActionListener(al);
        this.botonConfiguraciones.addActionListener(al);
        this.botonPartidaLibre.addActionListener(al);
        this.botonPuzzleDados.addActionListener(al);
        this.botonTorneo.addActionListener(al);
        this.botonVerPerfil.addActionListener(al);
    }
    public JButton getbotonCerrarSesion(){
        return botonCerrarSesion;
    }
    public JButton getbotonConfiguraciones(){
        return botonConfiguraciones;
    }
    public JButton getbotonPartidaLibre(){
        return botonPartidaLibre;
    }
    public JButton getbotonPuzzleDados(){
        return botonPuzzleDados;
    }
    public JButton getbotonTorneo(){
        return botonTorneo;
    }
    public JButton getbotonVerPerfil(){
        return botonVerPerfil;
    }
    
  
}
